name: build-artifacts

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 17.0.1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build artifacts
        run: ./gradlew clean build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: build-artifacts
          path: build/libs
