name: Check License

on:
  push:
    branches:
      - 1.18-3.0.0

jobs:
  run-license-check:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17.0.1'
        distribution: temurin
        cache: 'gradle'
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute licenseCheck
      run: ./gradlew --info --stacktrace checkLicenses
