name: Check License

on:
  push:
    branches:
      - 1.18-3.0.0
      - 1.18.2+-4.x.x
jobs:
  run-license-check:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.1'
          distribution: temurin
          cache: 'gradle'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Execute licenseCheck
        run: ./gradlew --info --stacktrace checkLicenses
